# See 04-using-actions/README.md for more information
# about using actions within workflows.

name: 04 - Using Actions

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: CWICZENIA/04-praca-z-zewnetrzymi-akcjami/react-app
    steps:
      # 1
      - name: Checkout Code
        uses: actions/checkout@v4
      # 2
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      # 3
      - name: Install Dependencies
        run: npm ci
      # 4
      - name: Run Unit Tests
        run: npm run test
