name: 05 - 2 - Event Filters and Activity Types

on:
  workflow_dispatch:
  pull_request:
    branches:
      - CW05
    types: [closed]

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Echo message
        run: echo "Running whenever a PR is closed."
