name: Build Docker image with actions/cache

on:
  push:
    branches: [ main ]
  pull_request:

defaults:
  run:
    shell: bash
    working-directory: ./CWICZENIA/13-caching/docker02

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Cache dla katalogu z warstwami buildx
      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: |
            /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-buildx-${{ hashFiles('Dockerfile', 'index.html') }}
          restore-keys: |
            ${{ runner.os }}-docker-buildx-

      - name: Build Docker image (with cached layers)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile

          # Bez pushowania do rejestru – przykład tylko do builda
          push: false
          tags: example-nginx:cache-actions-layers

          # Wskazanie katalogu z cache’em buildx
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
